services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress-web
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secrect
      WORDPRESS_DB_NAME: WPdb
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: WPdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secrect
      MYSQL_ROOT_PASSWORD: secrect
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin-db-console
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
