services:
  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress-web
    ports:
      - '80:80'
    env_file:
      - ./env/wordpress.env
    volumes:
      - /mnt/ebs/html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-db
    env_file:
      - ./env/mysql.env
    volumes:
      - /mnt/ebs/db_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin-db-console
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
